yamate0 <- read.csv("ch111.csv",header=T,row.names=1,fileEncoding="UTF8")
yamate1 <- as.dist(yamate0)
yamatesi <- hclust(yamate1,method="single")
plot(yamatesi)
yamateco <- hclust(yamate1,method="complete")
plot(yamateco)
yamateav <- hclust(yamate1,method="average")
plot(yamateav)
yamatece <- hclust(yamate1,method="centroid")
plot(yamatece)
yamatewa <- hclust(yamate1,method="ward.D2")
plot(yamatewa)
