train <- read.csv("ch141.csv",h=T)
valid <- read.csv("ch142.csv",h=T)
library(nnet)
sin1 <- nnet(output~input,data=train,size=2,maxit=1000)
yosoku1 <- predict(sin1,valid)  
plot(valid,type="b",pch=16,ylim=c(0,1))
points(train,pch=16,col="2")
points(valid$input,yosoku1,pch=16,col="4")
lines(valid$input,yosoku1)